/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.sgm.Vista;

import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author daryl
 */
public class FRM_Canciones extends javax.swing.JFrame {

    /**
     * Creates new form FRM_Canciones
     */
    public FRM_Canciones() {
        initComponents();
    }
    
    public static void getMensaje(String msj){
        JOptionPane.showMessageDialog(null, msj);
    }
    
    /*Recibe un actionlistener y se lo envía a los metodos de los 2 paneles
    para que lo asignen a los componentes que escuchan algún evento*/
    public void escuchadorMain(ActionListener manejador){
        this.panelBotones1.escucharBotones(manejador);
        this.panelDatosCancion1.escuchador(manejador);
    }//Fin del escuchador
    
    public PanelBotones getPanelBotones(){
        return this.panelBotones1;
    }
    
    public PanelDatosCancion getPanelDatosCancion() {
        return this.panelDatosCancion1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones1 = new ucr.ac.cr.sgm.Vista.PanelBotones();
        panelDatosCancion1 = new ucr.ac.cr.sgm.Vista.PanelDatosCancion();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelDatosCancion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosCancion1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ucr.ac.cr.sgm.Vista.PanelBotones panelBotones1;
    private ucr.ac.cr.sgm.Vista.PanelDatosCancion panelDatosCancion1;
    // End of variables declaration//GEN-END:variables
}
