/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ucr.ac.cr.sgm.Vista;

import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;
import ucr.ac.cr.sgm.Modelo.Cancion;

/**
 *
 * @author daryl
 */
public class PanelDatosCancion extends javax.swing.JPanel {

    /**
     * Creates new form PanelDatosCancion
     */
    public PanelDatosCancion() {
        initComponents();
    }
    
    /*Metodo que recibe un objeto y carga la información de dicho objeto
    en los campos correspondientes*/
    public void setCancion(Cancion cancion){
        this.txtTitulo.setText(cancion.getTitulo());
        this.txtDuracion.setText(""+cancion.getDuracion());
        this.txtGenero.setText(cancion.getGenero());
        this.txtAnnoLanzamiento.setText(""+cancion.getAnnoLanzamiento());
    }
    
    public Cancion getCancion(){
        return new Cancion( this.txtTitulo.getText(), 
            this.txtGenero.getText(), 
            Integer.parseInt(this.txtDuracion.getText()),
            Integer.parseInt(this.txtAnnoLanzamiento.getText()));
    } 
    
    public void limpiar(){
        this.txtTitulo.setText("");
        this.txtDuracion.setText("0");
        this.txtAnnoLanzamiento.setText("0");
        this.txtGenero.setText("");
    }
    
    public void cargarCombo(String[] listaTitulos){
        this.cboxTitulos.setModel(new DefaultComboBoxModel<>(listaTitulos));
    }
    
    public String devolverCombo(){
        return this.cboxTitulos.getSelectedItem().toString();
    }
    
    public void escuchador(ActionListener manejador){
        this.cboxTitulos.addActionListener(manejador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtGenero = new javax.swing.JTextField();
        txtAnnoLanzamiento = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        cboxTitulos = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Registro Canciones");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 6, -1, -1));

        jLabel3.setText("Título:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel4.setText("Genero:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel5.setText("Año Lanzamiento:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("Duración:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 150, -1));
        add(txtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 150, -1));

        txtAnnoLanzamiento.setText("0");
        add(txtAnnoLanzamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, -1));

        txtDuracion.setText("0");
        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });
        add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 150, -1));

        cboxTitulos.setActionCommand("ComboTitulos");
        add(cboxTitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 50, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxTitulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAnnoLanzamiento;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtGenero;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
